name: Docker Builder Image

on:
  push:
    tags:
      - '202[2-9].[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./builder.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=${{ github.ref_name }}
          push: true
          tags: 3dgi/geoflow-bundle-builder:${{ github.ref_name }}
          cache-from: type=registry,ref=3dgi/geoflow-bundle-builder:buildcache
          cache-to: type=registry,ref=3dgi/geoflow-bundle-builder:buildcache,mode=max